---
title: Find Alexander Galbreath m. Ann McPherson in 1881
---

$h2{Summary}

Alexander Galbraith m. Ann McPherson in 1881.
   Marriage says there were 21 and 18, but those are actually the
   "minimum" ages (as discovered looking at others).

This family has 2-3 children

$ul{
$li{Daniel/Don Galbraith b. 1884, d. 1946, m. Goldie Mitchell b. 1892-1971}
$li{Ethel may Galbraith b. 1890, d. 1966 in Parkersburg, VW., m. Blair Plate Sr.}
$li{Maybe a un-named still-born infant in 1887.}
}

Death cert of Don, says parents are from Scotland.

1900 Census for Ethel shows her living with a McPherson family as a Niece.  Head of household is Thomas aged 60, born Aug 1840 in Scotland.  His wife Emily is listed as being born in ohio, along with the rest of their children. 

This Thomas is $elink[https://www.familysearch.org/en/tree/person/details/LZXV-331]{Thomas McPherson} with spouse "Emily S. Plumly". He is from Southend, Argyll.

Their children are also listed as moving to Belpre, Washington Ohio.  of note:

$ul{
$li{A sister Ann, listed as being born in 1848}
$li{A brother Alexander McPherson who... Married Margaret Galbraith.}
}

In Ohio, a separate person needed to "sponsor" the application for marriage:

$ul{
$li{In 1881, for Alexander Galbreath, the sponsor was... Alexander McPherson.}
$li{In 1884, For Thomas McPherson, the sponsor was ... Alexander Galbraith.}
}
(Unable to find equiv for Alexander McPherson and Margaret Galbraith.)

Also:
$ul{
$li{There is another $child-link[galbreath-alexander-1816-mccualskey]{Alexander Galbraith} m. Elisabeth McCualskey who immigrated to Belpre.}
$li{In Southend, $child-link[galbraith-niel-abt-1801-mcpherson]{Niel Galbraith} m. Mary McPherson.}
}

At this point:
$ul{
$li{Ann, Thomas, and Alexander McPherson are siblings, and known.}
$li{Alexander and Margaret Galbraith are siblings.}
}

But who are Alexander and Margaret?  Guesing:

$ul{
$li{From Southend}
$li{Have a father named Donald (based on first son).}
$li{Born 1840-1850}
}

No Alexander matched, even expanding beyond these criterion nothing stood out. 

However a Margaret did match.  She's the daughter of Donald Galbraith and Janet Montgomery, born 1846 in Southend.  My original notes said "No additional information after 1851 census. Perhaps immigrated?"  and it listed the details from the 1851 census.

And lo.

$blockquote{$pre{
Alexander	Galbraith	Son	-	6	1845	Southend	
Margaret	Galbraith	-	-	4	1847	Southend
}
}

So in summary:

$child-link[galbraith-alexander-1844-mcpherson]{Alexander Galbraith}, b. abt 1844 in southend, the son of $child-link[galbraith-donald-abt-1815-montgomery]{Donald Galbraith} and Janet Montgomery.  He married Ann McPherson, b. abt 1848 in Southend, the daughter of $child-link[mcpherson-alexander-1810-mcconachy]{Alexander McPherson} and Helen McConachy.

And similarly for $child-link[galbraith-margaret-1846-mcpherson]{Margaret Galbraith} and Alexander McPherson.

Phew!


$hr{}

Long stream of conciousness version

While researching 

It turned up a marriage between an Alexander Galbreath and Annie McPherson on 1881 in Belpre, Washington, Ohio.

This didn't match the Alexander I was looking for.

Searching for these two in FamilySearch, turns up three autogenerated people and a bunch of hints.  I'm the first one looking into this.

Ok merging the three, along with 3 autogenerated spouses, along with some hints, ends up with:

Alexander Galbraith, 
Anna McPherson m. 1881

Daniel/Don Galbraith b. 1884, d. 1946, m. Goldie Mitchell b. 1892-1971

Ethel may Galbraith b. 1890, d. 1966 in Parkersburg, VW., m. Blair Plate Sr.

And maybe a un-named still-born infant in 1887.

After filling out their spouses and children from various hints, we get back to "Who is Alexander?"

Let's review the sources for data that isn't indexed.


The marriage certificate from 1881 says Alexander is 21 (~1860) and Annie is 18 (~1863).

The death certficate of his son Don, says his parents are from Scotland.  Ok!

I skipped the 1900 Census hint for their daughter Ethel since it looks too complicated.  Now that all the others are filled out, let's review.

She's 10 years old, and listed as a neice living in the household of Thomas McPherson.   Thomas is 60, born Aug 1840 in Scotland.  His wife Emily is listed as being born in ohio, along with the rest of their children. 

Back to Scotlands People to find Thomas.

There are actually two Thomas McPhersons born in Aug 1840. One from Falkirk, One from Southend, Argyll.   hmmmm....


Ok to recap....

Alexander Galbreath:  B ~ 1860 in Scotland, M. in 1881 in Ohio. 
TODO: check Census 1880, 1870, check death

Anna McPherson: B ~1863 in Scotland, M. in 1881 in Ohio
   Somehow related to Thomas McPherson b ~ 1840

Poking around
This $elink[https://www.familysearch.org/tree/person/details/LZXV-331]{Thomas} born in aug 1840 does have a younger sister Anne. but born in 1848.   A 15 year different in age would be ... impresive.

Ok let's look at Alexander.. b. in 1860... maybe in Census of 1861.

There's a lot.

Ok it's not Alexander, born 1859, son of $child-link[galbreath-donald-1819-mclean]{Donald Galbreath} and Isabella McLean... he shows up in the 1881 census.

Back to McPherson Family in 1900.  One son is listed as being born in 1885

Plugging in Thomas McPherson 1840 and Emily into FS... we find them 

$elink[https://www.familysearch.org/tree/person/details/L4JD-JHB]

The spouse is "Emily S. Plumly".


Ahh looking at sources, the 1900 Census is already attached to them.

Let's look at the marriage license in 1884.

WHAT THE ....

Alexander Galbraith is listed as the one "making the application" for Thomas and Emily (apperently that was needed in Ohio at the time).


AND.. looking at Alexander Galbreath's marriage application, it was a Alexander McPherson who made applicaton.  Alexander McPherson has to be Anna's brother.

Ok going to save that for later.


Back to Thomas. Thomas McPherson has a death date of 1913, oddly find-a-grave not linked or hinted.

Searching... found it.  Attaching.

Death cert lists Alexander McPherson and Ellen McDonehey as moth.

Ok... going back to Scotlands People and referencing FamilySearch

Ok Thomas is $elink[https://www.familysearch.org/tree/person/details/LZXV-331]{Thomas McPherson}, baptized 25 Aug 1840 in Southend.  He has a younger brother Alexander, and younger sister Anna.


Thomas has the Census of 1841 attached to him... lots of "unfinished attachements".. fixed.. looks good.  Here's the southend with his parents and older sister Janet.


No other census matches

Older sis Janet... moved to Washington Co... married in southend in 1857.

Anne, b. 1848 has 0 sources.. need to revisit this

And... youngest child "Alexander Donald" McPherson (doubt name is correct) also moved to Belpre, Washington, OH... AND married Margaret Galbraith.

I'm guessing this is a Alexander's sister. Claim: born 1846 from Berwickshire,Scotland... but...  Family Search for her is a mess... two different Margarets are all mixed up. 

One claim is death of 25-aug-1920 ... no death cert in FS... trying Findagrave nope.

Looking at marriage... 25-dec-1873

OHHHH.  Ok this isn't that useful but it's printed up an more or less says men need to be 21, women need to be 18.   SO I think Alexander and Ann weren't "21" and "18" ... that was just the minimums, and it's indexed incorrectly.

The actually image for Alexander McP and Margaret G isn't indexed so I have go look through a bunch of films.  Looking.. they are boring and have no ages or anything useful.  Skip!

Anyways.. Margaret Galbraith was born before 1873-18 = 1855.
Alexander McP is 1849 (unconfirmed but suspect it's fine).

And Alexander G was born BEFORE 1860, and Anna McP before 1863

We think Anna was 1848, so likely Alexander G was 1840-1850?


Looking for Alexanders in the OPR didn't turn up anything obvious.

Trying Margaret.

Margaret Galbraith, b. 15 Jan 1846, bp. 15 Feb 1846, daughter of Donald Galbraith b. ~1815 m. Janet Montgomery look good.

Does she have brother named Alexander?

No.

Yes!  He's not in the OPR but is in the family's Census of 1851, born about 1845.


